config/routes.rb
Rails.application.routes.draw do

  resources :staging_to_prods
  root 'static_pages#home'
  get 'static_pages/home'

  resources :venues

  resources :stagingtoprods

  get 'login/create'

  get 'login/get'

  post 'login/create'

  post 'login/get'

end

app/models/staging_to_prod.rb
class StagingToProd < ActiveRecord::Base
end

app/controllers/staging_to_prods_controller.rb
class StagingToProdsController < ApplicationController
  before_action :set_staging_to_prod, only: [:show, :edit, :update, :destroy]

  # GET /staging_to_prods
  # GET /staging_to_prods.json
  def index
    @staging_to_prods = StagingToProd.all
  end

  # GET /staging_to_prods/1
  # GET /staging_to_prods/1.json
  def show
  end

  # GET /staging_to_prods/new
  def new
    @staging_to_prod = StagingToProd.new
  end

  # GET /staging_to_prods/1/edit
  def edit
  end

  # POST /staging_to_prods
  # POST /staging_to_prods.json
  def create
    @staging_to_prod = StagingToProd.new(staging_to_prod_params)

    respond_to do |format|
      if @staging_to_prod.save
        format.html { redirect_to @staging_to_prod, notice: 'Staging to prod was successfully created.' }
        format.json { render :show, status: :created, location: @staging_to_prod }
      else
        format.html { render :new }
        format.json { render json: @staging_to_prod.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staging_to_prods/1
  # PATCH/PUT /staging_to_prods/1.json
  def update
    respond_to do |format|
      if @staging_to_prod.update(staging_to_prod_params)
        format.html { redirect_to @staging_to_prod, notice: 'Staging to prod was successfully updated.' }
        format.json { render :show, status: :ok, location: @staging_to_prod }
      else
        format.html { render :edit }
        format.json { render json: @staging_to_prod.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staging_to_prods/1
  # DELETE /staging_to_prods/1.json
  def destroy
    @staging_to_prod.destroy
    respond_to do |format|
      format.html { redirect_to staging_to_prods_url, notice: 'Staging to prod was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staging_to_prod
      @staging_to_prod = StagingToProd.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staging_to_prod_params
      params.fetch(:staging_to_prod, {})
    end
end

app/helpers/staging_to_prods_helper.rb
module StagingToProdsHelper
end

app/views/staging_to_prods/_form.html.erb
<%= form_for(@staging_to_prod) do |f| %>
  <% if @staging_to_prod.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staging_to_prod.errors.count, "error") %> prohibited this staging_to_prod from being saved:</h2>

      <ul>
      <% @staging_to_prod.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/staging_to_prods/edit.html.erb
<h1>Editing Staging To Prod</h1>

<%= render 'form' %>

<%= link_to 'Show', @staging_to_prod %> |
<%= link_to 'Back', staging_to_prods_path %>

app/views/staging_to_prods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Staging To Prods</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staging_to_prods.each do |staging_to_prod| %>
      <tr>
        <td><%= link_to 'Show', staging_to_prod %></td>
        <td><%= link_to 'Edit', edit_staging_to_prod_path(staging_to_prod) %></td>
        <td><%= link_to 'Destroy', staging_to_prod, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staging to prod', new_staging_to_prod_path %>

app/views/staging_to_prods/new.html.erb
<h1>New Staging To Prod</h1>

<%= render 'form' %>

<%= link_to 'Back', staging_to_prods_path %>

app/views/staging_to_prods/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_staging_to_prod_path(@staging_to_prod) %> |
<%= link_to 'Back', staging_to_prods_path %>