config/routes.rb
Rails.application.routes.draw do

  resources :staging_to_prods
  root 'static_pages#home'
  get 'static_pages/home'

  resources :venues

  resources :stagingtoprods

  get 'login/create'

  get 'login/get'

  post 'login/create'

  post 'login/get'

end

app/models/venue.rb
class Venue < ActiveRecord::Base
  validates :title,  presence: true
  validates :cover_image_url,  presence: true
  validates :description,  presence: true
  # associates attribute :image with a file attachment
  has_attached_file :avatar, {
	    :styles => {
		    thumb: '100x100>',
		    square: '200x200#',
		    medium: '340x340>',
		    large:  '500x500>'
	    },
            #:path =>  "/{image_path}/:id/:style/:filename"
        storage: :s3,
        s3_credentials: {access_key_id: ENV["AWS_ACCESS_KEY_ID"], secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"]},
        bucket: ENV["S3_BUCKET_NAME"]		    
      }

     # Validate the attached image is image/jpg, image/png, etc
     validates_attachment :avatar, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

      def set_path
      	  image_path = "venues/:id/:filename"
      end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show, :edit, :update, :destroy]

  # GET /venues
  # GET /venues.json
  def index
    @venues = Venue.all
  end

  # GET /venues/1
  # GET /venues/1.json
  def show
  end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # GET /venues/1/edit
  def edit
  end

  # POST /venues
  # POST /venues.json
  def create
    @venue = Venue.new(venue_params)
    @venue.uuid = SecureRandom.uuid
    respond_to do |format|
      if @venue.save
        format.html { redirect_to @venue, notice: 'Venue was successfully created.' }
        format.json { render :show, status: :created, location: @venue }
      else
        format.html { render :new }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venues/1
  # PATCH/PUT /venues/1.json
  def update
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
        format.json { render :show, status: :ok, location: @venue }
      else
        format.html { render :edit }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    @venue.destroy
    respond_to do |format|
      format.html { redirect_to venues_url, notice: 'Venue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venue_params
      params.require(:venue).permit(:uuid, :title, :description, :cover_image_url, :avatar)
    end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.erb
<%= form_for(@venue, multipart: true) do |f| %>
  <% if @venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% @venue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :cover_image_url %><br>
    <%= f.text_field :cover_image_url %>
  </div>
  <div class="field">
   <%= f.label :cover_image %>
   <%= f.file_field :cover_image %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/venues/edit.html.erb
<h1>Editing Venue</h1>

<%= render 'form' %>

<%= link_to 'Show', @venue %> |
<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Venues</h1>

<table>
  <thead>
    <tr>
      <th>Uuid</th>
      <th>Title</th>
      <th>Description</th>
      <th>Cover image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @venues.each do |venue| %>
      <tr>
        <td><%= venue.uuid %></td>
        <td><%= venue.title %></td>
        <td><%= venue.description %></td>
        <td><%= venue.cover_image_url %></td>
        <td><%= link_to 'Show', venue %></td>
        <td><%= link_to 'Edit', edit_venue_path(venue) %></td>
        <td><%= link_to 'Destroy', venue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Venue', new_venue_path %>

app/views/venues/new.html.erb
<h1>New Venue</h1>

<%= render 'form' %>

<%= link_to 'Back', venues_path %>

app/views/venues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uuid:</strong>
  <%= @venue.uuid %>
</p>

<p>
  <strong>Title:</strong>
  <%= @venue.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @venue.description %>
</p>

<p> <strong>Cover image</strong>  </p>
<img src= <%= @venue.cover_image_url %>  alt="Mountain View">
<p> 
<%= link_to 'Edit', edit_venue_path(@venue) %> |
<%= link_to 'Back', venues_path %>
</p>